# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    # use the empty dummy box
    config.vm.box = "dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # default provisioning script
    config.vm.provision :shell, path: "./../../bootstrap_base.sh"
    config.vm.provision :shell, path: "./provision/bootstrap.sh"
    config.vm.provision :shell, path: "./../bootstrap_desktop.sh"
    config.vm.provision :shell, path: "./../../bootstrap_cleanup.sh"



    # Use Virtualbox by default
    config.vm.provider "virtualbox"
    config.vm.provider "aws"

    # VirtualBox Provider-specific configuration
    config.vm.provider "virtualbox" do |vb, override|
    
        # set the name
        vb.name = "kali-linux-web-gui"

        # set the basebox to be Debian Jessie 64-bit, w/ 20 GB storage   
        # @see https://atlas.hashicorp.com/apolloclark
        override.vm.box = "apolloclark/debian-jessie-64"
        override.vm.box_url =" https://atlas.hashicorp.com/apolloclark/boxes/debian-jessie-64/versions/0.0.1/providers/virtualbox.box"

        # set the CPU, memory, acceleration
        # @see https://www.virtualbox.org/manual/ch08.html
        vb.cpus = 1
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
        vb.customize ["modifyvm", :id, "--pae", "on"]
        
        # Customize graphic
        vb.gui = true
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
        
        # Share a folder to the guest VM, types: docker, nfs, rsync, smb, virtualbox
        # Windows supports: smb
        # Mac supports: rsync, nfs
        # override.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"
        override.vm.synced_folder "./data", "/vagrant"
        
        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        # override.vm.network "forwarded_port", guest: 5900, host: 5900
 
        # setup local apt-get cache
        # if Vagrant.has_plugin?("vagrant-cachier")
            # Configure cached packages to be shared between instances of the same base box.
            # More info on the "Usage" link above
            # override.cache.scope = :box
        # end
    end



    # configuration when deploying to Amazon
    config.vm.provider :aws do |aws, override|
    
        # Load sensitive AWS credentials from external file, DO NOT save in Repo!!!
        # @see http://blog-osshive.rhcloud.com/2014/02/05/provisioning-aws-instances-with-vagrant/
        require 'yaml'
        aws_filepath = File.dirname(__FILE__) + "/../../aws-config.yml"
        if File.exist?(aws_filepath)
            aws_config  = YAML.load_file(aws_filepath)["aws"]
        else
            print "Error: '" + aws_filepath + "' is missing...\n"
        end
        
        # set AWS creds
        aws.access_key_id             = aws_config["access_key_id"]
        aws.secret_access_key         = aws_config["secret_access_key"]
        aws.keypair_name              = aws_config["keypair_name"]
        
        # configure SSH... and fuck Windows file pathways...
        override.ssh.private_key_path = aws_config["pemfile"]
        override.ssh.username         = "admin"

        # use Debian / Jessie 64-bit HVM
        # @see https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie
        aws.region = "us-east-1"
        aws.ami = "ami-116d857a"
            # "ami-116d857a" HVM
            # "ami-896d85e2" Paravirtualization
        
        # set instance settings
        # @see https://aws.amazon.com/ec2/instance-types/
        aws.instance_ready_timeout    = 180
        aws.instance_type             = "t2.large"
        aws.associate_public_ip       = true
        aws.subnet_id                 = aws_config["subnet_id"]
        aws.tags = {
            'Name' => 'kali-linux-web-gui',
        }
        # use 40GB, because we like it UUGE!
        aws.block_device_mapping = [
            {
                'DeviceName' => '/dev/xvda',
                'VirtualName' => 'root',
                'Ebs.VolumeSize' => 40,
                'Ebs.DeleteOnTermination' => 'true'
            }
        ]

        # Configure file sharing using rsync.
        # This requires Windows users to have Cygwin or MinGW installed.
        # @see https://www.vagrantup.com/blog/feature-preview-vagrant-1-5-rsync.html
        # @see https://github.com/mitchellh/vagrant/blob/master/website/docs/source/v2/synced-folders/rsync.html.md
        override.vm.synced_folder "./data", "/vagrant", type: "rsync"
        # , disabled: true
        
        # Fix for Windows users running Cygwin:
        if Vagrant::Util::Platform.windows?
            ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
        end
        # To continuously update files bi-directionally, open another shell, run:
        # "vagrant rsync-auto"
    
        # disable the vbguest update plugin
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = false
        end
    end
end
