# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

    # use the empty dummy box
    config.vm.box = "dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # default provisioning script
    config.vm.provision :shell, path: "./../../bootstrap_base.sh"
    config.vm.provision :shell, path: "./provision/bootstrap.sh"
    config.vm.provision :shell, path: "./../../bootstrap_cleanup.sh"



    # Use Virtualbox by default, before Amazon
    config.vm.provider "virtualbox"
    config.vm.provider "aws"

    # VirtualBox Provider-specific configuration
    config.vm.provider "virtualbox" do |vb, override|
    
        # set the name
        vb.name = "kali-linux-rfid-cli"
    
        # Display the VirtualBox GUI when booting the machine
        vb.gui = false

        # Customize the amount of memory on the VM:
        vb.memory = "1024"

        # set the base box to Debian Jessie, 64-bit
        # @see https://atlas.hashicorp.com/apolloclark
        override.vm.box = "apolloclark/debian-jessie-64"
        override.vm.box_url =" https://atlas.hashicorp.com/apolloclark/boxes/debian-jessie-64/versions/0.0.1/providers/virtualbox.box"
    
        # Share a folder to the guest VM, types: docker, nfs, rsync, smb, virtualbox
        # Windows supports: smb
        # Mac supports: rsync, nfs
        # override.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"
        override.vm.synced_folder "./data", "/vagrant"
    
        # setup cache
        # if Vagrant.has_plugin?("vagrant-cachier")
            # Configure cached packages to be shared between instances of the same base box.
            # More info on the "Usage" link above
            # override.cache.scope = :box
        # end
    end





    # configure AWS provider
    config.vm.provider "aws" do |aws, override|
    
        # Load sensitive AWS credentials from external file, DO NOT save in Repo!!!
        # @see http://blog-osshive.rhcloud.com/2014/02/05/provisioning-aws-instances-with-vagrant/
        require 'yaml'
        aws_filepath = File.dirname(__FILE__) + "./../../aws-config.yml"
        if File.exist?(aws_filepath)
            aws_config  = YAML.load_file(aws_filepath)["aws"]
        else
            print "Error: '" + aws_filepath + "' is missing...\n"
        end
        
        # set AWS creds
        aws.access_key_id             = aws_config["access_key_id"]
        aws.secret_access_key         = aws_config["secret_access_key"]
        aws.keypair_name              = aws_config["keypair_name"]
        
        # configure SSH
        override.ssh.private_key_path = aws_config["pemfile"]
        override.ssh.username         = "admin"

        # use Debian / Jessie 64-bit HVM
        # @see https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie
        aws.region = "us-east-1"
        aws.ami = "ami-116d857a"
            # "ami-116d857a" HVM
            # "ami-896d85e2" Paravirtualization
        
        # set instance settings
        # @see https://aws.amazon.com/ec2/instance-types/
        aws.instance_ready_timeout    = 180
        aws.instance_type             = "t2.small"
        aws.associate_public_ip       = true
        aws.subnet_id                 = aws_config["subnet_id"]
        aws.tags = {
            'Name' => 'kali-linux-rfid-cli',
        }
        
        # disable local file sharing, to prevent issues with Windows hosts
        override.vm.synced_folder "./data", "/vagrant", disabled: true
    
        # disable the vbguest plugin
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = false
        end
    end
end
